# Site settings
title: 马鹏飞的博客
SEOTitle: 马鹏飞的博客 | Pengfei Blog
header-img: img/home-bg-1.jpeg
email: mapengfei@mail.nwpuedu.cn
description: "这里是马鹏飞的个人博客，与你一起发现更大的世界 | 一个研究心脏的程序员"
#url: "https://huangxuan.me" # your host, for absolute URL
url: "https://shaoyaoqian.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
weibo_username: u/5336841337
zhihu_username: mafgghyffggy
github_username: shaoyaoqian
twitter_username: mpf_npu

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: pengfeima

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "一个研究心脏的程序员 <br> 西北工业大学"
sidebar-avatar: https://raw.githubusercontent.com/mapengfei-nwpu/personal_pictures/main/typora_picgo/202210101547925.JPG # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
# friends:
#   [
#     { title: "乱序（Midare）", href: "http://mida.re/" },
#     { title: "Ebn Zhang", href: "https://ebnbin.dev/" },
#     { title: "Kun Qian", href: "http://kunq.me" },
#     { title: "Sherry Woo", href: "https://sherrywoo.me/" },
#     { title: "SmdCn", href: "http://blog.smdcn.net" },
#     { title: "JiyinYiyong", href: "http://tiye.me/" },
#     { title: "DHong Say", href: "http://dhong.co" },
#     { title: "尹峰以为", href: "http://ingf.github.io/" },
#   ]
