# Site settings
title: 马鹏飞的博客
author: 马鹏飞
SEOTitle: 马鹏飞的博客 | Pengfei Blog
header-img: img/home-bg-1.jpeg
email: mapengfei@mail.nwpuedu.cn
description: "这里是马鹏飞的个人博客，与你一起发现更大的世界 | 一个研究心脏的程序员"
url: "https://www.pengfeima.cn" # host, for absolute URL
baseurl: ""                     # '/blog' if your blog is hosted on 'host/blog'

# Social network settings
weibo_username: u/5336841337
zhihu_username: mafgghyffggy
github_username: shaoyaoqian
twitter_username: mpf_npu
wechat_username: mfmpf1996

# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
  ]

# A JavaScript utility for adding deep anchor links to existing page content.
anchorjs: true

# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Support local preview for Jekyll 3.0
# Make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# document: http://jekyllrb.com/docs/configuration/markdown/
markdown: kramdown

# Sidebar settings
sidebar: true                                                          # Whether or not using Sidebar.
sidebar-about-description: "一个研究心脏的程序员 <br> 西北工业大学"      # Personal description
sidebar-avatar: img/portrait.jpg                                       # Personal avatar

# Featured Tags
featured-tags: true         # whether or not using Feature-Tags
featured-condition-size: 1  # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Waline comment system.
# for more information : https://waline.js.org/guide/get-started.html
comments_domain: waline.pengfeima.cn

# Friends
friends:
  [
    { title: "Frytea", href: "https://blog.frytea.com" },
    { title: "乱序（Midare）", href: "http://mida.re/" },
    { title: "Ebn Zhang", href: "https://ebnbin.dev/" },
    { title: "Kun Qian", href: "http://kunq.me" },
    { title: "Sherry Woo", href: "https://sherrywoo.me/" },
    { title: "SmdCn", href: "http://blog.smdcn.net" },
    { title: "JiyinYiyong", href: "http://tiye.me/" },
    { title: "DHong Say", href: "http://dhong.co" },
    { title: "尹峰以为", href: "http://ingf.github.io/" },
  ]