#################################################################
###################### NexT Configuration #######################
#################################################################
# See: https://theme-next.js.org/docs/

# ============================================================= #
# ============= Theme Core Configuration Settings ============= #
# ============================================================= #

# Remove unnecessary files after hexo generate.
minify: true

custom_file_path:
  head: source/_data/head.njk
  header: source/_data/header.njk
  sidebar: source/_data/sidebar.njk
  postMeta: source/_data/post-meta.njk
  postBodyEnd: source/_data/post-body-end.njk
  footer: source/_data/footer.njk
  bodyEnd: source/_data/body-end.njk
  variable: source/_data/variables.styl
  mixin: source/_data/mixins.styl
  style: source/_data/styles.styl


# ============================================================= #
# ====================== Scheme Settings ====================== #
# ============================================================= #

scheme: Gemini
#scheme: Muse
#scheme: Mist
#scheme: Pisces
darkmode: true


# ============================================================= #
# ================= Site Information Settings ================= #
# ============================================================= #

favicon:
  small: /images/favicon-16x16-next.png
  medium: /images/favicon-32x32-next.png
  apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo.svg
  # android_manifest: /images/manifest.json

# custom_logo: /img/logo-blue.png


# ============================================================= #
# ======================= Menu Settings ======================= #
# ============================================================= #

menu:
  life: /life/ || fas fa-pizza-slice
  observer: /observer/ || fas fa-eye
  notes: /notes/ || fas fa-book
  culture: /culture/ || fas fa-guitar
  album: /album/ || fas fa-camera-retro
  guestbook: /guestbook/ || fas fa-splotch
  archives: /timeline/ || fa fa-archive

menu_settings:
  icons: true

# ============================================================= #
# ===================== Sidebar Settings ====================== #
# ============================================================= #

avatar:
  url: /img/portrait.png
  rounded: true

site_state: false

social:
  微博: https://www.weibo.com || fa-brands fa-weibo
  哔哩哔哩: https://www.bilibili.com || fa-brands fa-bilibili
  # RSS: /atom.xml || fas fa-rss

social_icons:
  icons_only: true

toc:
  number: false
  wrap: true # 超出范围文字是否换行
  max_depth: 3 # <h3> ###
  expand_all: true

# ============================================================= #
# ====================== Footer Settings ====================== #
# ============================================================= #

footer:
  since: 2023
  icon:
    name: fas fa-heart
    animated: true
    color: "#f06292"
  copyright: Shaoyaoqian
  powered: false


# ============================================================= #
# ======================= Post Settings ======================= #
# ============================================================= #

read_more_btn: false

post_meta:
  item_text: false
  updated_at:
    enable: false

tag_icon: true

# Show previous post and next post in post footer if exists
post_navigation: right


# ============================================================= #
# ==================== Misc Theme Settings ==================== #
# ============================================================= #

preconnect: false

theme_color:
  light: "#e7ddc8"
  dark: "#181c27"

codeblock:
  # All available themes: https://theme-next.js.org/highlight/
  prism:
    light: prism
    dark: prism-okaidia
  copy_button:
    enable: true
    style: flat

back2top:
  scrollpercent: true



# ============================================================= #
# =============== Third Party Services Settings =============== #
# ============================================================= #

# Math Formulas Render Support
# See: https://theme-next.js.org/docs/third-party-services/math-equations
math:
  mathjax:
    enable: false
    tags: ams
pjax: false
fancybox: true
lazyload: true
pangu: true

# Dependencies: https://github.com/next-theme/hexo-generator-searchdb
local_search:
  enable: false


# ============================================================= #
# ======================== Tag Plugins ======================== #
# ============================================================= #

# Note tag (bootstrap callout)
note:
  style: flat
  icons: true
  light_bg_offset: 0

# Tabs tag
tabs:
  sticky: true
  transition:
    tabs: true
    labels: true


# ============================================================= #
# ==================== Animation Services ===================== #
# ============================================================= #

motion:
  enable: true


# ============================================================= #
# ==================== External Libraries ===================== #
# ============================================================= #
# See: https://theme-next.js.org/docs/advanced-settings/vendors

vendors:
  # local | jsdelivr | unpkg | cdnjs | custom
  internal: custom
  plugins: custom
  custom_cdn_url: https://cdn.staticfile.org/${cdnjs_name}/${version}/${cdnjs_file} #七牛云 不支持latest 海外阿里云
  #custom_cdn_url: https://lib.baomitu.com/${cdnjs_name}/${version}/${cdnjs_file} #360 75CDN 海外亚马逊云
  #custom_cdn_url: https://jsd.pinlyu.com/npm/${npm_name}@${version}/${minified}

# Waline
# For more information: https://waline.js.org, https://github.com/walinejs/waline
waline:
  enable: false #是否开启
  serverURL: waline.pengfeima.cn # Waline #服务端地址，我们这里就是上面部署的 Vercel 地址
  locale:
    placeholder: 疑义相与析，畅所欲言，不登录也没关系哒 # #评论框的默认文字
  avatar: mm # 头像风格
  dark: auto
  meta: [nick,mail,link] # 自定义评论框上面的三个输入框的内容
  pageSize: 10 # 评论数量多少时显示分页
  lang: zh-cn # 语言, 可选值: en, zh-cn
  visitor: true # 文章阅读统计
  comment_count: true # 如果为 false , 评论数量只会在当前评论页面显示, 主页则不显示
  requiredFields: [] # 设置用户评论时必填的信息，[nick,mail]: [nick] | [nick, mail]
  libUrl: https://cdn.staticfile.org/waline/2.14.7/waline.min.js
  cssUrl: https://cdn.staticfile.org/waline/2.14.7/waline.min.css
