
# https://theme-next.js.org/docs/theme-settings/

scheme: Gemini
#scheme: Muse
#scheme: Mist
#scheme: Pisces
darkmode: true
custom_file_path:
  # head: source/_data/head.njk
  #header: source/_data/header.njk
  #sidebar: source/_data/sidebar.njk
  #postMeta: source/_data/post-meta.njk
  # postBodyEnd: source/_data/post-body-end.njk
  footer: source/_data/footer.html
  # bodyEnd: source/_data/body-end.njk
  variable: source/_data/variables.styl
  # mixin: source/_data/mixins.styl
  style: source/_data/styles.styl




favicon:
  small: /images/favicon-16x16-next.png
  medium: /images/favicon-32x32-next.png
  apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo.svg
  android_manifest: /images/manifest.json

custom_logo: /img/logo-blue.png


creative_commons:
  # Available values: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | cc-zero
  license: by-nc-sa
  # Available values: big | small
  size: small
  sidebar: true
  post: true
  language: deed.zh


open_graph:
  enable: true
  # Add pairs each line to customize
  options:
    type: blog


menu:
  home: / || fa fa-home
  life: /life/ || fas fa-pizza-slice
  observer: /observer/ || fas fa-eye
  notes: /notes/ || fas fa-book
  culture: /culture/ || fas fa-guitar
  album: /album/ || fas fa-camera-retro
  guestbook: /guestbook/ || fas fa-splotch
  #  default: /guestbook/ || fas fa-splotch
  #  links: ../links/ || fas fa-link
  #about: /about/ || fa fa-user
  #tags: /tags/ || fa fa-tags
  #categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  #schedule: /schedule/ || fa fa-calendar
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat


# menu:
#   home: / || fa fa-home
#   archives: /archives/ || fa fa-archive
#   Docs:
#     default: /docs/ || fa fa-book
#     Getting Started:
#       default: /getting-started/ || fa fa-flag
#       Installation: /installation.html || fa fa-download
#       Configuration: /configuration.html || fa fa-wrench
#     Third Party Plugins:
#       default: /third-party-services/ || fa fa-puzzle-piece
#       Math Equations: /math-equations.html || fa fa-square-root-alt
#       Comment Systems: /comments.html || fa fa-comment-alt


menu_settings:
  icons: true




# ============================================================= #
# ===================== Sidebar Settings ====================== #
# ============================================================= #

avatar:
  url: /img/portrait.png
  rounded: true

site_state: false

social:
  微博: https://dlzhang.com/weibo || fa-brands fa-weibo
  哔哩哔哩: https://dlzhang.com/bilibili || fa-brands fa-bilibili
  RSS: /atom.xml || fas fa-rss

social_icons:
  icons_only: true

toc:
  number: false
  wrap: true # 超出范围文字是否换行
  max_depth: 3 # <h3> ###
  expand_all: true

# ============================================================= #
# ====================== Footer Settings ====================== #
# ============================================================= #

footer:
  since: 2017
  icon:
    name: fas fa-heart
    animated: true
    color: "#f06292"
  copyright: Shaoyaoqian
  powered: false