name: Tag release

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag "release-$(date +%Y%m%d)"
        git push origin "release-$(date +%Y%m%d)"