name: Tag release

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get current date
      id: date
      run: echo "::set-env name=CURRENT_DATE::$(date +%Y%m%d)"

    - name: Create tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag "release-${{ env.CURRENT_DATE }}"
        git push origin "release-${{ env.CURRENT_DATE }}"